[system]
owner_id = "" # Input your Discord user ID here. If empty this will use bot.owner_id
restart_on_crash = true

[beacon]
enable_platform_whitelist = true
enabled_platforms = ["discord", "stoat", "fluxer"]