[system]
restart_on_crash = true

[beacon]
enable_platform_whitelist = true
enabled_platforms = [
    "discord",
    "stoat",
    "fluxer",
]
enable_private_spaces = true
enable_public_spaces = true
enable_agegated_spaces = false
max_spaces_per_server = 10
